In [1]:
import numpy as np
from scipy.stats import norm
from src.scale import scale
from src.sim import sim
from model.pcr import PCR
from model.pls import PLS
from model.ridge import Ridge

x = np.loadtxt("./data/x.txt", delimiter=",")
y = np.loadtxt("./data/y.txt", delimiter=",")
index = np.loadtxt("./data/index.txt.", delimiter=",", dtype=bool)
names = np.loadtxt("./data/names.txt", delimiter=",", dtype=str)
x, _, _ = scale(x)
x_train = x[index]
x_test = x[~index]
y_train = y[index]
y_test = y[~index]
n, p = x_train.shape

In [2]:
pcr1 = PCR(x_train, y_train, list(names[0:p]), is_scale=True, is_var_exp=False)
pcr1.pcr()
pcr1.cv(n)
pcr1.report_coe()
pcr1.predict_err(x_test, y_test)
pcr1.test_err(x_test, y_test)

best n_component: 8


array([ 2.46493292,  0.67952814,  0.26305307, -0.14146483,  0.21014656,
        0.3052006 , -0.28849277, -0.02130504,  0.26695576])

inter    lcavol   lweight       age      lbph       svi       lcp  \
1  2.440814  0.181365  0.066062  0.104853  0.013198  0.171073  0.201367   
2  2.434918  0.188250  0.180227  0.198568  0.158167  0.132167  0.163195   
3  2.453944  0.283007  0.303216  0.071021  0.136638  0.277941  0.235467   
4  2.470647  0.273531  0.305169 -0.065729  0.234396  0.252737  0.253925   
5  2.471598  0.301113  0.259699 -0.054716  0.267891  0.257811  0.262847   
6  2.482040  0.414788  0.282458 -0.077279  0.219226  0.132881  0.272116   
7  2.497368  0.541209  0.290594 -0.152550  0.214104  0.317523 -0.050312   
8  2.464933  0.679528  0.263053 -0.141465  0.210147  0.305201 -0.288493   

    gleason     pgg45     cverr  
1  0.176262  0.188318  0.856101  
2  0.163631  0.159104  0.798878  
3 -0.034045  0.050945  0.681801  
4  0.002599  0.097587  0.665796  
5 -0.010629  0.078329  0.691716  
6  0.013823  0.050035  0.713314  
7  0.232852 -0.061243  0.639056  
8 -0.021305  0.266956  0.583955

0.5212740056508927

best n_component: 7
err: 0.44830894430680407


err_mean   err_std
1  0.545192  0.174140
2  0.720011  0.237154
3  0.514112  0.132185
4  0.536946  0.127903
5  0.540274  0.126829
6  0.479880  0.122634
7  0.448309  0.104437
8  0.521274  0.178724

In [3]:
pls1 = PLS(x_train, y_train, list(names[0:p]), is_scale=True, is_var_exp=False)
pls1.pls()
pls1.cv(n)
pls1.report_coe()
pls1.predict_err(x_test, y_test)
pls1.test_err(x_test, y_test)

best n_component: 6


array([ 2.46515591,  0.67383924,  0.26542406, -0.14351015,  0.21060265,
        0.31241993, -0.29171062, -0.01520278,  0.26453211])

inter    lcavol   lweight       age      lbph       svi       lcp  \
1  2.447253  0.266063  0.166871  0.086432  0.099716  0.210022  0.186835   
2  2.466966  0.413932  0.324013 -0.021280  0.241138  0.255679  0.085696   
3  2.483213  0.566887  0.281624 -0.182171  0.202991  0.307838 -0.036917   
4  2.478764  0.669269  0.261006 -0.176330  0.237177  0.281053 -0.232140   
5  2.468582  0.683982  0.266730 -0.137330  0.199134  0.311617 -0.285056   
6  2.465156  0.673839  0.265424 -0.143510  0.210603  0.312420 -0.291711   
7  2.464917  0.679485  0.262404 -0.141256  0.210731  0.305841 -0.288538   
8  2.464933  0.679528  0.263053 -0.141465  0.210147  0.305201 -0.288493   

    gleason     pgg45     cverr  
1  0.133464  0.165000  0.726832  
2  0.006269  0.081127  0.633383  
3  0.006491  0.118421  0.608787  
4  0.062550  0.189226  0.596215  
5  0.015419  0.219961  0.586564  
6 -0.015203  0.264532  0.582375  
7 -0.021403  0.266684  0.583961  
8 -0.021305  0.266956  0.583955

0.521221995662384

best n_component: 3
err: 0.4284325870322826


err_mean   err_std
1  0.536988  0.153989
2  0.536420  0.149277
3  0.428433  0.113253
4  0.499736  0.154569
5  0.504146  0.167984
6  0.521222  0.178167
7  0.521327  0.178626
8  0.521274  0.178724

In [11]:
lam = np.arange(0, 16, 1)
ridge1 = Ridge(x_train, y_train, list(names[0:p]), lam=lam, is_scale=True)
ridge1.ridge()
ridge1.cv(n)
ridge1.report_coe()
ridge1.predict_err(x_test, y_test)
ridge1.test_err(x_test, y_test)

best lambda: 4


array([ 2.4668892 ,  0.59454251,  0.25870101, -0.11502386,  0.20193212,
        0.28486059, -0.17973515,  0.00853173,  0.20779895])

inter    lcavol   lweight       age      lbph       svi       lcp  \
1   2.464933  0.679528  0.263053 -0.141465  0.210147  0.305201 -0.288493   
2   2.465739  0.654683  0.262265 -0.134185  0.208110  0.299482 -0.255541   
3   2.466294  0.632532  0.261240 -0.127380  0.206053  0.294226 -0.226934   
4   2.466662  0.612606  0.260037 -0.121005  0.203990  0.289369 -0.201870   
5   2.466889  0.594543  0.258701 -0.115024  0.201932  0.284861 -0.179735   
6   2.467009  0.578061  0.257265 -0.109401  0.199887  0.280657 -0.160052   
7   2.467046  0.562935  0.255753 -0.104105  0.197861  0.276721 -0.142444   
8   2.467019  0.548984  0.254184 -0.099109  0.195858  0.273021 -0.126609   
9   2.466942  0.536058  0.252575 -0.094389  0.193881  0.269532 -0.112299   
10  2.466828  0.524034  0.250935 -0.089922  0.191933  0.266231 -0.099314   
11  2.466683  0.512807  0.249274 -0.085690  0.190014  0.263098 -0.087485   
12  2.466516  0.502292  0.247601 -0.081673  0.188127  0.260117 -0.076672   
13  2.466331  0.492414  0.245920 -0.077858  0.186272  0.257272 -0.066757   
14  2.466133  0.483108  0.244236 -0.074228  0.184449  0.254553 -0.057638   
15  2.465925  0.474319  0.242554 -0.070772  0.182658  0.251947 -0.049230   
16  2.465710  0.466000  0.240877 -0.067478  0.180899  0.249445 -0.041457   

     gleason     pgg45     cverr  lam  
1  -0.021305  0.266956  0.583955    0  
2  -0.011417  0.247998  0.579660    1  
3  -0.003436  0.232265  0.577336    2  
4   0.003102  0.219040  0.576311    3  
5   0.008532  0.207799  0.576168    4  
6   0.013095  0.198149  0.576637    5  
7   0.016973  0.189794  0.577539    6  
8   0.020301  0.182502  0.578752    7  
9   0.023184  0.176094  0.580190    8  
10  0.025703  0.170427  0.581792    9  
11  0.027919  0.165386  0.583514   10  
12  0.029885  0.160878  0.585326   11  
13  0.031639  0.156826  0.587203   12  
14  0.033215  0.153168  0.589127   13  
15  0.034638  0.149851  0.591087   14  
16  0.035929  0.146832  0.593070   15

0.49686539682046743

best lambda: 12
err: 0.4872683633807763


err_mean   err_std  lam
1   0.521274  0.178724    0
2   0.512403  0.174005    1
3   0.505738  0.170354    2
4   0.500694  0.167507    3
5   0.496865  0.165280    4
6   0.493964  0.163537    5
7   0.491781  0.162180    6
8   0.490162  0.161132    7
9   0.488990  0.160336    8
10  0.488176  0.159749    9
11  0.487652  0.159334   10
12  0.487363  0.159063   11
13  0.487268  0.158915   12
14  0.487333  0.158871   13
15  0.487531  0.158915   14
16  0.487838  0.159035   15